services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: jeevan
      POSTGRES_PASSWORD: ${Db_password}
      POSTGRES_DB: grac_db
    ports:
      - "5432:5432"  # Added this so you can use pgAdmin!
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./database/01_schema.sql:/docker-entrypoint-initdb.d/01_init.sql
      - ./database/02_seed.sql:/docker-entrypoint-initdb.d/02_seed.sql
    networks:
      - grac_network

# You must define the "items" you used above here:
volumes:
  db_data:

networks:
  grac_network: