services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: jeevan
      POSTGRES_PASSWORD: secure_password
      POSTGRES_DB: grac_db
    ports:
      - "5432:5432"  # Added this so you can use pgAdmin!
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/init.sql
      - ./database/seed.sql:/docker-entrypoint-initdb.d/data.sql
    networks:
      - grac_network

# You must define the "items" you used above here:
volumes:
  db_data:

networks:
  grac_network: